FROM alpine:3.6
MAINTAINER Mark Myers <marcusmyers@gmail.com>

ENV VAULT_VERSION=0.8.1

RUN apk add --update unzip \
      bash \
      ca-certificates \
    && rm -rf /var/cache/apk/*

ADD https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip /tmp
RUN cd /tmp \
    && unzip vault_${VAULT_VERSION}_linux_amd64.zip \
    && mv vault /usr/local/bin \
    && rm -f vault_${VAULT_VERSION}_linux_amd64.zip

EXPOSE 8200

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]
CMD [ "server", "-dev" ]
