FROM alpine:3.5
MAINTAINER Mark Myers <marcusmyers@gmail.com>

RUN apk add --update unzip \
      bash \
      ca-certificates \
    && rm -rf /var/cache/apk/*

ADD https://releases.hashicorp.com/vault/0.7.2/vault_0.7.2_linux_amd64.zip /tmp
RUN cd /tmp \
    && unzip vault_0.7.2_linux_amd64.zip \
    && mv vault /usr/local/bin \
    && rm -f vault_0.7.2_linux_amd64.zip

EXPOSE 8200

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]
CMD [ "server", "-dev" ]
