#!/usr/bin/env php

<?php
require "vendor/autoload.php";
use Illuminate\Support\Collection;
use Graze\ParallelProcess\Pool;
use Graze\ParallelProcess\Table;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Process\Process;

class Dockerfile {
    protected $file;
    protected $arrFileContent;

    public function __construct(String $filepath)
    {
        $this->file = $filepath;
    }

    public function dir()
    {
        return pathinfo($this->file, PATHINFO_DIRNAME);
    }

    public function dependent_image()
    {
        $this->arrFileContent = file($this->file)[0];
        return $this->arrFileContent;
    }

    public function dependent_on_marcusmyers()
    {
        if(preg_match("/marcusmyers/", $this->dependent_image())){
            return true;
        } else {
            return false;
        }
    }

    public function image_tag()
    {
        return "marcusmyers/". ( strpos($this->dir(), "/") ? preg_replace("/\//", ":", $this->dir()) : $this->dir() . ":latest");
    }

    public function build_push_image()
    {
        return new Process("docker build -t ". $this->image_tag() . " " . $this->dir() . "&& docker push " . $this->image_tag(). " && docker rmi " . $this->image_tag());
    }
}

$output = new ConsoleOutput(ConsoleOutput::VERBOSITY_VERY_VERBOSE);

$dfiles = Collection::make(array_merge(glob('*/Dockerfile'), glob('*/*/Dockerfile')));

$dockerfiles = $dfiles->map(function ($file) {
    return new Dockerfile($file);
});

$marcusmyers_dependent_images = $dockerfiles->filter( function($file) {
    return $file->dependent_on_marcusmyers();
});

$non_marcusmyers_dependencies = $dockerfiles->reject( function($file) {
    return $file->dependent_on_marcusmyers();
});

$pool1 = new Pool();
$pool2 = new Pool();

$pool1->setMaxSimultaneous(4);
$ppol2->setMaxSimultaneous(6);

$table1 = new Table($output, $pool1);
$table2 = new Table($output, $pool2);

$non_marcusmyers_dependencies->each(function ($d) use ($table1) {
  $table1->add($d->build_push_image());
});
$table1->run();

$marcusmyers_dependent_images->each(function ($d) use ($table2) {
  $table2->add($d->build_push_image());
});
$table2->run();
