#!/usr/bin/env php

<?php

class Dockerfile {
  protected $file;

  public function __construct(String $filepath)
  {
    $this->file = $filepath;
  }

  public function dir()
  {
    return pathinfo($this->file, PATHINFO_DIRNAME);
  }

  public function image_tag()
  {
    return "marcusmyers/". ( strpos($this->dir(), "/") ? preg_replace("/\//", ":", $this->dir()) : $this->dir() . ":latest");
  }

  public function build_push_image()
  {
    echo "RUNNING: docker build -t ". $this->image_tag() . " " . $this->dir() . "\n";
    system("docker build -t ". $this->image_tag() . " " . $this->dir());
    system("docker push " . $this->image_tag());
  }
}

$dfiles = array_merge(glob('*/Dockerfile'), glob('*/*/Dockerfile'));

$dockerfiles = [];

foreach($dfiles as $file) {
  $dockerfile = new Dockerfile($file);
  $dockerfile->build_push_image();
}
